### ISSUE TITLE
1.1.0 breaks require() usage

### ISSUE THREAD

**Issue by BigBlueHat** [privatenumber/cli-simple-table#22]
Looks like the build process changes between `1.0.0` and `1.1.0` broke the ability to use this as a Common JS module. Here's what I get post upgrade:

```
TypeError: SimpleTable is not a constructor
```
or sometimes
```
Cannot find module 'cli-simple-table'
```
or from eslint
```
import/no-unresolved: Unable to resolve path to module 'cli-simple-table'.
```

Versions:
NPM: 6.14.13
Node: v14.17.3

**Comment by privatenumber** [comment]
Thanks for reporting! Hope v1.1.1 resolves it

I believe the ESLint warning is because the import plugin (maybe the version you're using), doesn't support export maps
